# Generated by Django 5.2.15 on 2026-06-17 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_calendarfeed_calendareventcache_feed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('duty_type', models.CharField(choices=[('worship_band', 'Worship Band'), ('catering', 'Catering'), ('kids_ministry', 'Kids Ministry')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('people', models.ManyToManyField(blank=True, related_name='sunday_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sunday duties',
                'ordering': ['date', 'duty_type'],
            },
        ),
        migrations.CreateModel(
            name='CateringDuty',
            fields=[
            ],
            options={
                'verbose_name': 'Catering roster',
                'verbose_name_plural': 'Catering roster',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('church.sundayduty',),
        ),
        migrations.CreateModel(
            name='KidsMinistryDuty',
            fields=[
            ],
            options={
                'verbose_name': 'Kids Ministry roster',
                'verbose_name_plural': 'Kids Ministry roster',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('church.sundayduty',),
        ),
        migrations.CreateModel(
            name='WorshipBandDuty',
            fields=[
            ],
            options={
                'verbose_name': 'Worship Band roster',
                'verbose_name_plural': 'Worship Band roster',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('church.sundayduty',),
        ),
        migrations.AddConstraint(
            model_name='sundayduty',
            constraint=models.UniqueConstraint(fields=('date', 'duty_type'), name='unique_sunday_duty_per_date_type'),
        ),
    ]
