# Generated by Django 5.2.15 on 2026-06-17 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_sundayduty_cateringduty_kidsministryduty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sundayplan',
            name='catering',
        ),
        migrations.RemoveField(
            model_name='sundayplan',
            name='host',
        ),
        migrations.RemoveField(
            model_name='sundayplan',
            name='kids_leaders',
        ),
        migrations.RemoveField(
            model_name='sundayplan',
            name='musicians',
        ),
        migrations.RemoveField(
            model_name='sundayplan',
            name='preacher',
        ),
        migrations.RemoveField(
            model_name='sundayplan',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='sundayplan',
            name='visuals',
        ),
        migrations.RemoveField(
            model_name='sundayplan',
            name='worship_leader',
        ),
        migrations.AddField(
            model_name='sundayplan',
            name='hosting',
            field=models.ManyToManyField(blank=True, related_name='hosting_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sundayplan',
            name='preaching',
            field=models.ManyToManyField(blank=True, related_name='preaching_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
