# Generated by Django 5.2.15 on 2026-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayduty',
            name='church_catering',
            field=models.BooleanField(default=False),
        ),
    ]
