# Generated by Django 5.2.15 on 2026-07-07 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_sundayduty_church_catering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterReminderCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_reminder_copies_to', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_reminder_copies_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roster reminder copy',
                'verbose_name_plural': 'Roster reminder copies',
                'ordering': ['volunteer__last_name', 'volunteer__first_name', 'recipient__last_name', 'recipient__first_name'],
                'constraints': [models.UniqueConstraint(fields=('volunteer', 'recipient'), name='unique_roster_reminder_copy')],
            },
        ),
    ]
