# Generated by Django 5.2.15 on 2026-07-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_rosterremindercopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('bible_study_zoom', 'Bible Study Zoom Details')], max_length=64, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
